from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


class BrowserStartError(Exception):
    pass


@runtime_checkable
class DriverProtocol(Protocol):
    """Selenium と Playwright 両方のドライバーが実装する共通インターフェース。"""

    def navigate(self, url: str) -> None: ...

    def do_click(self, selector: str, timeout: float) -> None: ...

    def do_fill(self, selector: str, value: str, timeout: float) -> None: ...

    def do_select(self, selector: str, value: str, timeout: float) -> None: ...

    def do_check(self, selector: str, checked: bool, timeout: float) -> None: ...

    def get_screenshot_png(self) -> bytes: ...

    def execute_js(self, script: str) -> Any: ...

    def get_window_handles(self) -> list[str]: ...

    def get_current_window_handle(self) -> str: ...

    def switch_to_window(self, handle: str) -> None: ...

    def close_current_window(self) -> None: ...

    def wait_for_new_window(self, known_handles: set[str], timeout: float) -> str: ...

    def quit(self) -> None: ...

    def __enter__(self) -> DriverProtocol: ...

    def __exit__(self, *args: Any) -> None: ...
